### PR TITLE
update dotnet recipes

### PR DESCRIPTION
**Pull request by karthago1**

### CODE REVIEW

**Comment by ajlennon** [comment]
Ah very good :) It's rather lovely to wake up and see  you've been contributing and checking and it all works !!! :-D

**Comment by karthago1** [comment]
yes the CI is working very well now. thanks to the helloworld test, it is faster to test with your CI than my PC :smiley:

**Comment by ajlennon** [comment]
Aaahaahahahah - that's hilarious. Makes sense to me too as I put a grunty machine on this precisely to speed things up !!!

**Comment by karthago1** [comment]
next week at work I will test the arm64 target, and then I will set this PR to Ready for review.
in the next weeks / months we will switch to dotnet 6. so we will test this recipe under arm64 very well

**Comment by ajlennon** [comment]
Awesome!

**Comment by karthago1** [comment]
@ajlennon these changes are also working for ARM64. (I made some simple tests)

**Comment by ajlennon** [comment]
Interesting. I think we should be able to do something to add to this line to build and test

https://github.com/DynamicDevices/meta-mono/blob/17bcd2e5fae8a76aa968e47dfc4a5a23f397d75f/.github/workflows/CI_github.yml#L20


        arch: [x86-64, arm]

to 

        arch: [x86-64, arm, arm64]

Maybe

**Comment by ajlennon** [comment]
Going back to our chat about moving from master to kirkstone, I see it seems to be completely rebuilding and it really shouldn't be. I'll have to have a look at why this is

**Comment by karthago1** [comment]
last time the CI was really fast.
maybe there is a rule to delete the sstate and artifacts after some days.

**Comment by ajlennon** [comment]
Maybe. Humm

**Comment by ajlennon** [comment]
Nice!

**Pull request merged**
