### PR TITLE
Msbuild replace libhostfxr with dotnet with fixes

### PR DESCRIPTION
**Pull request by zboszor**
Fixes #163

### CODE REVIEW

**Comment by zboszor** [comment]
@ajlennon All checks passed with my fixes.

**Comment by ajlennon** [comment]
Great stuff! Merged thanks @zboszor

**Comment by ajlennon** [comment]
Hi @zboszor - I've just moved master to build against langdale and am getting an error relating to msbuild. Any thoughts if it's related to this PR?

https://github.com/DynamicDevices/meta-mono/actions/runs/4583026156/jobs/8103940764#step:7:15017

**Comment by zboszor** [comment]
> Hi @zboszor - I've just moved master to build against langdale and am getting an error relating to msbuild. Any thoughts if it's related to this PR?
> 
> https://github.com/DynamicDevices/meta-mono/actions/runs/4583026156/jobs/8103940764#step:7:15017

It's not. I am seeing it in Mickledore, too. This is something Yocto warns about now, and is unrelated to this PR.

FWIW, I see this in a lot of `python3-*`  modules, too. Even with ones present in oe-core or meta-oe that contains pyx files and are preprocessed into C sources and built into a binary .so with cython.

**Pull request merged**
