### PR TITLE
dotnet: add dotnet v7.0.202

### PR DESCRIPTION
**Pull request by karthago1**
hello!

maybe it is time to add a new recipe :)

### CODE REVIEW

**Comment by ajlennon** [comment]
Great stuff thanks! Could you have a quick look at this warning please?

image

**Comment by ajlennon** [comment]
Can I also suggest that you pin the version of dotNet to default to this in `layer.conf` ?

https://github.com/DynamicDevices/meta-mono/blob/master/conf/layer.conf

**Comment by karthago1** [comment]
> Great stuff thanks! Could you have a quick look at this warning please?
> 
> image

I just ignored that 

`INSANE_SKIP:${PN}-dbg = "libdir"`

since dotnet is not following the linux philosophy :).

**Comment by karthago1** [comment]
> Can I also suggest that you pin the version of dotNet to default to this in `layer.conf` ?
> 
> https://github.com/DynamicDevices/meta-mono/blob/master/conf/layer.conf

do you want to pin the dotnet version to 6.0.403 in the master branch? (usually the master branch uses the latest versions)

**Comment by ajlennon** [comment]
>do you want to pin the dotnet version to 6.0.403 in the master branch? (usually the master branch uses the latest versions)

Whatever you think best - which is the current release version? Would it be better to use 6.x or 7.x?

**Comment by karthago1** [comment]
- 6.x is the current LTS
- 7.x is the latest release
- (8 is still in preview)

I wouldn't pin the 7.x version, because yocto picks up the latest version by default. but if you want to pin the 6.x for some reasons, then we have to do it the layer.conf.

**Comment by karthago1** [comment]
but maybe we should pin the version and let yocto take always the latest version. (especially in the master branch)

**Comment by karthago1** [comment]
@ajlennon you switched the CI to Langdale, which will reach its EOL next month.
Kirkstone is an LTS version and will be support at least until Apr. 2024. (maybe more)

**Comment by ajlennon** [comment]
>Kirkstone is an LTS version and will be supported at least until Apr. 2024. (maybe more)

Yeah - I actually want master building against whatever the latest release is, so shortly mickledore, but I wanted to go through langdale first to make sure that builds before I flip to mickledore next :)

**Comment by ajlennon** [comment]
We seem to be getting there. Just getting this now

` FileExistsError: File already exists: /__w/meta-mono/meta-mono/langdale/build/tmp/work/core2-64-poky-linux/python3-pythonnet/3.0.1+gitAUTOINC+e28dd80c3a-r0/image/usr/lib/python3.10/site-packages/clr.py`

**Comment by karthago1** [comment]
I rebased on the latest commit (in the master branch). maybe it will work now

**Comment by ajlennon** [comment]
>I rebased on the latest commit (in the master branch). maybe it will work now

Looks like it's building!

**Comment by ajlennon** [comment]
Brilliant! Thanks for that!

**Comment by ajlennon** [comment]
>I wouldn't pin the 7.x version, because yocto picks up the latest version by default. but if you want to pin the 6.x for some reasons, then we have to do it in the layer.conf.

I've added control of the version of dotnet we build for test with CI to the GitHub workflow now. So it should do the same as what we do for Mono itself

**Pull request merged**
