### PR TITLE
add Python.NET recipe

### PR DESCRIPTION
**Pull request by Livius90**
Python.NET (pythonnet) is a package that gives Python programmers nearly seamless integration with .NET Framework, .NET Core and Mono runtime on Windows, Linux and macOS. Python.NET provides a powerful application scripting tool for .NET developers. Using this package you can script .NET applications or build entire applications in Python, using .NET services and components written in any language that targets the CLR (C#, VB.NET, F#, C++/CLI).
http://pythonnet.github.io/

Python.NET uses flit-core package for installing. Flit-core is supported since Yocto kirkstone release.

### CODE REVIEW

**Comment by Livius90** [comment]
@ajlennon 
Can you help and share some info about your proxy in your test build? In pythonnet and clr-loader recipe there is a "dotnet restore" which can not work well in your test build. I got this same issue in my Yocto project, i could solve it with the following [proxy variable defines](https://github.com/DynamicDevices/meta-mono/pull/159/files#diff-a5a462720a6819941622a14ad5887b9df96fa125ad92d049d9fb3e630b5d6f1aR42).

**Comment by ajlennon** [comment]
Hi @Livius90 I'm not really following I'm afraid as there shouldn't be a proxy in place in the CI build as far as I know?

**Comment by ajlennon** [comment]
Ah! I recall something about this now. Yocto now disallows internet access by default during compile steps unless it is specifically configured to support this. There are some notes in an issue here but I can't find them at the moment

**Comment by Livius90** [comment]
As i understand nuget package manager are integrated in dotnet and pythonnet and clr-loader .NET projects like to trigger a "dotnet restore" command to restore all of nuget packs from internet. Is it possible somehow let it to get an internet connection? In my local company machine i got the same issue but it caused by my incorrect proxy settings, now it is different a little in your CI built test.

**Comment by Livius90** [comment]
@ajlennon 
I tested your proxy setting with the following commit: https://github.com/DynamicDevices/meta-mono/pull/159/commits/76a6a45838352869c5fb3626cb187a8c32d1cdaa
As i see, you use a docker for build-and-test action and in [bitbake log](https://github.com/DynamicDevices/meta-mono/actions/runs/3492404795/jobs/5846147822#step:7:87) `http_proxy` and `https_proxy` env variables are totally empty, it means `dotnet restore` can not use a correct proxy settings to download nugets.

Do you know what should be these proxy variables for your docker?

That same issue was in my company machine too, i could [solve it nicely](https://github.com/DynamicDevices/meta-mono/pull/159/files#diff-0ffdc047d7ceee9d228c70895ddc0362870a0e2d354ef66683ec4e2cf8929e84R36) by a pre-defined `DOTNET_HTTP_PROXY` and `DOTNET_HTTPS_PROXY` variable in local.conf.

**Comment by ajlennon** [comment]
Hi - well we can change the envvars if you think it'll help? I still don't really understand why it would be needed but we could give it a go. I would think we could set these in the GitHub YAML. I'm out diving in Egypt until next week but maybe could could try a PR with that which the CI could build in the meantime ?

**Comment by Livius90** [comment]
> 

I do not know what is your proxy and docker details. I can try to set `http_proxy` and `https_proxy` variables to an url value what you can give me first. But probably need any further proxy settings in your docker config too before.

**Comment by ajlennon** [comment]
Well this is what I don't understand. I have no proxy setup and it all works fine... the container access the internet constantly to download source...

**Comment by Livius90** [comment]
In my company's Linux machine i got `http_proxy=http://127.0.0.1:3128` in default Linux environment because we have an installed NTLM. Inside bitbake, `dotnet restore` was failed always for me also with the same errors but when i did `dotnet restore` manually in my terminal, it works, magically. I know that this local proxy IP just forwarding the proxy request to an `http://my.copmany.com:3128` url, finaly i tried to override `http_proxy` and `https_proxy` to this direct domain url and it was started to work well for `dotnet restore` command in bitbake task, too.

There are some many really similar problem in GitHub issues, there some hints to change any other NUGET env variables to solve, it i will try these things soon.
https://github.com/NuGet/Home/issues/6978

**Comment by ajlennon** [comment]
There is no proxy... the container accesses the internet directly...

**Comment by Livius90** [comment]
> There is no proxy... the container accesses the internet directly...

Just for try i put a webcontent downloading in bitbake task and it seems, internet access is not healthy in your docker, curl can not reach api.nuget.org where the nuget package sources is available.

`curl: (6) Could not resolve host: api.nuget.org`

https://github.com/DynamicDevices/meta-mono/actions/runs/3555147656/jobs/5971666960#step:7:11572

**Comment by ajlennon** [comment]
> Is DNS configured well in your docker?

Well I am having a look but I can't see how it's possible that DNS is generally broken as the docker container is constantly downloading lots of source files from the Internet...

**Comment by ajlennon** [comment]
OK so I have entered the docker container and I can see I can retrieve the json file OK...

image

**Comment by Livius90** [comment]
Hm, it means somewhy in the bitbake compiler task environment the network accessability is different somehow then in your normal docker terminal console has. Possibble it is a docker vs, Yocto bitbake vs, dotnet triple network issue, there are some issue tickets with the similar problem, there were some hints to use hard DNS address and other ideia was to set a metric/priority settings for multiple ethernet LAN connections, if it has, but unfortunately these issues was closed without final solution.

That problem is realy big issue because a Yocto recipe can use dotnet-native for any simple cross-compilation for .NET 6.0 apps but if their apps have any nuget depedency it can be easily failed in a docker container. For me in my phisical copmany's Ubuntu Linux machine i got only a proxy missconfiguration problem, i could solve it quickly via the `http_proxy` environment variables. Probably on any non-proxy and non-docker building Linux machines can use well dotnet-native in a recipes but this situation is not so nice, if it randomly can not work or can work in a docker containers.

**Comment by ajlennon** [comment]
` SyntaxError: unexpected character after line continuation character`

**Comment by Livius90** [comment]
I could not leave [DOTNET_HTTP_PROXY definition](https://github.com/DynamicDevices/meta-mono/pull/159/files#diff-a5a462720a6819941622a14ad5887b9df96fa125ad92d049d9fb3e630b5d6f1aR46) in my last test. My company's proxy work well only if i pre-define it in my local.conf. Usage of `do_compile[network] = "1"` does not matter for it.

**Comment by Livius90** [comment]
@ajlennon 
How can we add a custom unit-test recipe for pythonnet on qemu machine target? We can execute the .NET core tests from pythonnet source easily like pythonnet action/workflow do it [here](https://github.com/pythonnet/pythonnet/blob/master/.github/workflows/ARM.yml#L47).

Need to just execute the follwoing command in tests folder of pythonnet repo.
```
python3 -m pytest --runtime coreclr
```

**Comment by ajlennon** [comment]
Merged in. That's great. We got there in the end and it also validates the whole CI testing setup for me.

You can probably enable unit testing on these recipes as Yocto supports this. 

The other way is to add some test classes as I've done for some specific simple tests which will be run during the CI build in QEMU

e.g.

https://github.com/DynamicDevices/meta-mono/tree/master/lib/oeqa/runtime/cases

**Pull request merged**
