### PR TITLE
Use scarthgap branch in CI build

### PR DESCRIPTION
**Pull request by Livius90**
Use scarthgap branch in CI build

### CODE REVIEW

**Comment by Livius90** [comment]
@ajlennon 
Can you check is there enough free space in CI build machine?

```
Exception: FileNotFoundError: [Errno 2] No such file or directory: '/__w/meta-mono/meta-mono/scarthgap/build/tmp/work/core2-64-poky-linux/gtk-sharp/2.12.45/packages-split/gtk-sharp-src/usr//usr'
```

**Comment by Livius90** [comment]
@ajlennon 
It seems to me `gtk-sharp 2.12.45` is no longer compatible with Yocto scarthgap due to this two package_rpm class changes:

https://github.com/yoctoproject/poky/commit/57d82f92c1060c5f15072f5d266dbac11665ae26
https://github.com/yoctoproject/poky/commit/347abb8c06b6a84ddd214d14964e049685a9be5f

**Comment by ajlennon** [comment]
Filesystem doen't seem to be full

**Comment by Livius90** [comment]
@ajlennon 
Do you know what recipe depend for `gtk-sharp_2.12.45` in the test build? Does it have any new release version which can be better to use?

**Comment by ajlennon** [comment]
@Livius90 I think we're going to have to work out what's wrong wiht the gtk-sharp recipe

**Comment by Livius90** [comment]
@ajlennon 
Lets see what happen
https://docs.yoctoproject.org/dev/ref-manual/variables.html?highlight=allow_empty#term-ALLOW_EMPTY

**Comment by Livius90** [comment]
ALLOW_EMPTY can not help. By the way i a have a bad feeling about why it has double `usr` folder in the end of the path. `... gtk-sharp-src/usr//usr`

```
2024-06-02T20:34:56.8423962Z ERROR: gtk-sharp-2.12.45-r0 do_package_write_rpm: Error executing a python function in exec_func_python() autogenerated:
2024-06-02T20:34:56.8425877Z 
2024-06-02T20:34:56.8427074Z The stack trace of python calls that resulted in this exception/failure was:
2024-06-02T20:34:56.8429267Z File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
2024-06-02T20:34:56.8430533Z      0001:
2024-06-02T20:34:56.8431070Z  *** 0002:write_specfile(d)
2024-06-02T20:34:56.8431707Z      0003:
2024-06-02T20:34:56.8434073Z File: '/__w/meta-mono/meta-mono/scarthgap/poky/meta/classes-global/package_rpm.bbclass', lineno: 525, function: write_specfile
2024-06-02T20:34:56.8436592Z      0521:            spec_scriptlets_bottom.append('')
2024-06-02T20:34:56.8437586Z      0522:
2024-06-02T20:34:56.8438104Z      0523:        # Now process files
2024-06-02T20:34:56.8438934Z      0524:        file_list = []
2024-06-02T20:34:56.8439927Z  *** 0525:        walk_files(root, file_list, conffiles, dirfiles)
2024-06-02T20:34:56.8441742Z      0526:        if not file_list and localdata.getVar('ALLOW_EMPTY', False) != "1":
2024-06-02T20:34:56.8443518Z      0527:            bb.note("Not creating empty RPM package for %s" % splitname)
2024-06-02T20:34:56.8444764Z      0528:        else:
2024-06-02T20:34:56.8445889Z      0529:            spec_files_bottom.append('%%files -n %s' % splitname)
2024-06-02T20:34:56.8448531Z File: '/__w/meta-mono/meta-mono/scarthgap/poky/meta/classes-global/package_rpm.bbclass', lineno: 249, function: walk_files
2024-06-02T20:34:56.8451311Z      0245:                    target.append(get_attr(dir) + '%dir "' + escape_chars(p) + '"')
2024-06-02T20:34:56.8452670Z      0246:            elif path:
2024-06-02T20:34:56.8453842Z      0247:                # packages own only empty directories or explict directory.
2024-06-02T20:34:56.8455495Z      0248:                # This will prevent the overlapping of security permission.
2024-06-02T20:34:56.8456842Z  *** 0249:                attr = get_attr(path)
2024-06-02T20:34:56.8458030Z      0250:                if (not files and not dirs) or path in dirfiles:
2024-06-02T20:34:56.8459715Z      0251:                    target.append(attr + '%dir "' + escape_chars(path) + '"')
2024-06-02T20:34:56.8460948Z      0252:
2024-06-02T20:34:56.8461471Z      0253:            for file in files:
2024-06-02T20:34:56.8463750Z File: '/__w/meta-mono/meta-mono/scarthgap/poky/meta/classes-global/package_rpm.bbclass', lineno: 203, function: get_attr
2024-06-02T20:34:56.8466817Z      0199:        # of the walk, the isdir() test would then fail and the walk code would assume its a file
2024-06-02T20:34:56.8468720Z      0200:        # hence we check for the names in files too.
2024-06-02T20:34:56.8469909Z      0201:        for rootpath, dirs, files in os.walk(walkpath):
2024-06-02T20:34:56.8470971Z      0202:            def get_attr(path):
2024-06-02T20:34:56.8472196Z  *** 0203:                stat_f = os.stat(rootpath + "/" + path, follow_symlinks=False)
2024-06-02T20:34:56.8473620Z      0204:                mode = stat.S_IMODE(stat_f.st_mode)
2024-06-02T20:34:56.8474546Z      0205:                try:
2024-06-02T20:34:56.8475363Z      0206:                    owner = pwd.getpwuid(stat_f.st_uid).pw_name
2024-06-02T20:34:56.8476477Z      0207:                except Exception as e:
2024-06-02T20:34:56.8480251Z Exception: FileNotFoundError: [Errno 2] No such file or directory: '/__w/meta-mono/meta-mono/scarthgap/build/tmp/work/cortexa15t2hf-neon-poky-linux-gnueabi/gtk-sharp/2.12.45/packages-split/gtk-sharp-src/usr//usr'
2024-06-02T20:34:56.8483553Z 
2024-06-02T20:34:56.8501954Z NOTE: recipe dotnet-native-6.0.423-r0: task do_create_spdx: Started
2024-06-02T20:34:56.8528776Z ERROR: Logfile of failure stored in: /__w/meta-mono/meta-mono/scarthgap/build/tmp/work/cortexa15t2hf-neon-poky-linux-gnueabi/gtk-sharp/2.12.45/temp/log.do_package_write_rpm.7425
2024-06-02T20:34:56.8532717Z NOTE: recipe gtk-sharp-2.12.45-r0: task do_package_write_rpm: Failed
2024-06-02T20:34:56.8684650Z ERROR: Task (/__w/meta-mono/meta-mono/scarthgap/meta-mono/recipes-mono/gtk-sharp/gtk-sharp_2.12.45.bb:do_package_write_rpm) failed with exit code '1'
```

**Comment by Livius90** [comment]
@ajlennon 
gtk-sharp issue is solved and from now there are no any warnings in the Yocto build also.

**Comment by ajlennon** [comment]
Great work @Livius90 !

**Pull request merged**
