### PR TITLE
dotnet: add dotnet 8 recipe

### PR DESCRIPTION
**Pull request by karthago1**
hello i hope we can integrate the new dotnet version

(I am still testing)

### CODE REVIEW

**Comment by ajlennon** [comment]
Hi there - not sure why the CI is failing. I'm off to FOSDEM and don't have my computer so it may be a few days before I can look at this

**Comment by karthago1** [comment]
take your time. I am still testing the recipe.

It is always the same with the CI, It stops working, if you take some days off :smile:

**Comment by Livius90** [comment]
We could try to build it from real source also.
https://github.com/dotnet/dotnet/tree/v8.0.1?tab=readme-ov-file#building

**Comment by karthago1** [comment]
yes we could. for the moment I would pickup the easiest tested path to get a working dotnet runtime. (but it is interesting if you try that path too.)

**Comment by ajlennon** [comment]
ok that's been quite a pain. dunno what happened to it but I'm having to reinstall the CI VM. That's building now but I remember getting QEMU running was also a pain so there's probably a bit more config. I need to do...

**Comment by ajlennon** [comment]
@karthago1 humm - it all took a while as building from scratch. It looks like the dotnet hello world recipe failed to build. Not entirely sure if this is a CI think or a PR thing. Given you're updating the dotNet framework maybe it's a PR thing? Could you have a quick look?

**Comment by karthago1** [comment]
of course I will check it

**Comment by Livius90** [comment]
@karthago1 
You should change to use .NET 8.0 CI build config in dotnet version "matrix" in .yml, also.
https://github.com/DynamicDevices/meta-mono/blob/master/.github/workflows/CI_github.yml#L20

Also i suggest to dropout one of them old dotnet version from master, because the automatic CI build will be really slow for all 3 kind of dotnet version for each 3 kind of arch. I would vote to dropout .NET 7 support in master from now, and keep only the LTS releases (.NET 6 and 8) in active recipes.

**Comment by karthago1** [comment]
>  I would vote to dropout .NET 7 support in master from now, and keep only the LTS releases (.NET 6 and 8) in active recipes.

Agree. I am still using dotnet 6 and trying to move to 8

**Comment by ajlennon** [comment]
Hmmm?

image

**Comment by Livius90** [comment]
@ajlennon 
At the moment something went wrog with qemu, it is any general issue with it, it seems to me not the dotnet 6.0 or 8.0 is the root cause:
```
Exception: RuntimeError: FAILED to start qemu - check the task log and the boot log
```

**Comment by ajlennon** [comment]
> @ajlennon At the moment something went wrog with qemu, it is any general issue with it, it seems to me not the dotnet 6.0 or 8.0 is the root cause:
> 
> ```
> Exception: RuntimeError: FAILED to start qemu - check the task log and the boot log
> ```

I'm not sure about that to be honest. What I am seeing is an error compiling the test executable as it thinks the .NET runtime is wrong?

**Comment by karthago1** [comment]
@ajlennon most probably this is a dotnet problem. I will check this. it is a new recipe, so things may have changed. (how to install dotnet). I wanted to use your CI for testing, but for some reason it was not so smooth. I will copy the recipe to my project and test it there first.

**Comment by ajlennon** [comment]
>I wanted to use your CI for testing, but for some reasons it was not so smooth.

Yeah the CI has all been a bit of a pain to setup again but hopefully we're there with it now!

**Comment by karthago1** [comment]
I have the same problem too. (i will fix it)

**Comment by karthago1** [comment]
maybe the CI is still having a little problem :smile_cat: . but I can successfully test the recipe `dotnet-helloworld` under `aarch64`

**Comment by ajlennon** [comment]
> maybe the CI is still having a little problem 😸 . but I can successfully test the recipe `dotnet-helloworld` under `aarch64`

Yeah there's a problem building with `/dev/kvm` support for `QEMU` just looking at that now

**Comment by karthago1** [comment]
I run the test with kirkstone on my machine. everything is fine. I will try mickledore maybe tomorrow

**Comment by Livius90** [comment]
@ajlennon 
It can be closed, dotnet 8 recipe added via another PR.

**Comment by karthago1** [comment]
@Livius90 thank you for the help

**Pull request closed without merging**
