### PR TITLE
Add honister compatibility

### PR DESCRIPTION
**Pull request by zboszor**

### CODE REVIEW

**Comment by ajlennon** [comment]
Wow that feels like a real breaking change. Not so keen on removing compatibility from the old releases but the syntax change requires it then? Why did they make such a bit breaking change?

**Comment by zboszor** [comment]
> Wow that feels like a real breaking change. Not so keen on removing compatibility from the old releases but the syntax change requires it then? Why did they make such a bit breaking change?

See this mail for the proposal that was implemented since then:
https://www.mail-archive.com/openembedded-architecture@lists.openembedded.org/msg00500.html

The necessary changes to bitbake accept `:` along with `_` as the override syntax separator was patched back to dunfell,
i.e. the current LTS Yocto release and newer (bitbake 1.46.x, 1.48.x, 1.50.x) but not older versions.

This is really a breaking change, there's no other way around it but to port newer recipes to older branches in meta-mono
and if newer Mono recipes appear, master (honister and later) and older branches will have to have differently written recipes.

**Comment by ajlennon** [comment]
Thanks - well if Richard thinks it is needed I'm not going to argue. Feels like it's going to cause trouble for people though.

Could you do me a favour and add those details into the commit message so people who run into trouble can more easily see in the history what broke their builds?

**Comment by zboszor** [comment]
> Thanks - well if Richard thinks it is needed I'm not going to argue. Feels like it's going to cause trouble for people though.
> 
> Could you do me a favour and add those details into the commit message so people who run into trouble can more easily see in the history what broke their builds?

Done.

**Comment by ajlennon** [comment]
Merged - thanks @zboszor !

**Pull request merged**
