### PR TITLE
Add support for mono 6.8 and the 6.xx branches

### LINKED ISSUE #18: Add support for mono 6.8.x

### PR DESCRIPTION
**Pull request by ThadHouse**
It requires a new base, as the license text changes, the file extension for the archives changed, and one of the patches no longer applies. 

Only tested with 6.8, and running a test right now at the link below to make sure it fully builds after cleaning up the repo.
https://dev.azure.com/thadhouse/Mono/_build/results?buildId=549&view=results

Closes #18

### CODE REVIEW

**Comment by ThadHouse** [comment]
The build finished, and I verified the binaries are actually built as 6.8 as well.

**Comment by ajlennon** [comment]
Thanks @ThadHouse !

**Comment by ajlennon** [comment]
Hmm - failing to build on my system

http://jenkins.dynamicdevices.co.uk:8080/job/meta-mono/156/console

**Comment by ThadHouse** [comment]
Hmm. That's odd, I don't think GTK was built with my build. That seems like an upstream issue however with that test, with the new c# 8 range functionality

**Comment by ajlennon** [comment]
Yup. I'm wondering how to disable tests in gtk-sharp

**Comment by ThadHouse** [comment]
https://github.com/mono/gtk-sharp/pull/263

It was fixed upstream last year, but a release was never done with the fix. So a patch likely could also fix the issue.

**Comment by ajlennon** [comment]
Excellent - thanks will take a look

**Comment by ajlennon** [comment]
@ThadHouse fixed in #f876db5f

**Pull request merged**
