### PR TITLE
Add msbuild 16.10.1 recipe

### PR DESCRIPTION
**Pull request by zboszor**
It fixes the error in our in-house project that is really an inconsistency between the older msbuild 16.6 and the newest Mono.

### CODE REVIEW

**Comment by ajlennon** [comment]
Seems unhappy on arm64?

**Comment by zboszor** [comment]
> Seems unhappy on arm64?

Does the CI still use 6.12.0.161 instead of the latest 6.12.0.182?

`MACHINE=qemuarm64 bitbake msbuild` succeeded for me on Mickledore with 6.12.0.182.

**Comment by ajlennon** [comment]
> Does the CI still use 6.12.0.161 instead of the latest 6.12.0.182?

Yes needs a bump then - 

https://github.com/DynamicDevices/meta-mono/blob/master/.github/workflows/CI_github.yml#L20

**Comment by zboszor** [comment]
FWIW, `MACHINE=qemuarm bitbake msbuild` also succeeded for me on Mickledore with 6.12.0.182

**Comment by ajlennon** [comment]
Not sure what's going on. The CI seems like it's blocked

**Comment by ajlennon** [comment]
Restarted the build but the arm64 msbuild seems to be erroring :'(

**Comment by zboszor** [comment]
> Restarted the build but the arm64 msbuild seems to be erroring :'(

It's TLS errors during `nuget restore`.

It's usually transient, or in case of an older OS, ca-certificates may be outdated.

Or `cert-sync` should be run. I will try this.

**Comment by ajlennon** [comment]
Great! Thanks @zboszor

**Pull request merged**
