### PR TITLE
Mickledore

### PR DESCRIPTION
**Pull request by ajlennon**

### CODE REVIEW

**Comment by ajlennon** [comment]
@Livius90 looks like it

**Comment by Livius90** [comment]
Can you merge it without squashing, now?

For me, in my forked repo i could do it nicely: https://github.com/Livius90/meta-mono/pull/1

**Comment by ajlennon** [comment]
Nope - still gives this "linear history" thing!

**Comment by Livius90** [comment]
> Nope - now it gives this "linear history" thing!

Wtf is this, why i did not have this issue for the same branch merging in my forked repo?

**Comment by ajlennon** [comment]
It's really weird itn's it. Dunno what's going on here!

**Comment by Livius90** [comment]
My last idea is to do it from git command line:
https://stackoverflow.com/a/5602109

**Pull request closed without merging**
