### PR TITLE
add dotnet 8 to kirkstone

### PR DESCRIPTION
**Pull request by karthago1**
just testing if the kirkstone branch is working fine. (since this is the only version I am using right now)

### CODE REVIEW

**Comment by ajlennon** [comment]
Awesome 🙌

**Comment by karthago1** [comment]
@ajlennon should we merge this PR? if someone is using the kirkstone branch and using dotnet 6, then he will get a free/unintentional upgrade to dotnet 8 :smile: .  this can be

**Comment by ajlennon** [comment]
Sounds good to me - to you want to remove draft status then?

**Comment by ajlennon** [comment]
Thanks!

**Pull request merged**
