### PR TITLE
Fix python3-pythonnet recipe build for langdale

### PR DESCRIPTION
**Pull request by Livius90**
Try to fix recipe install issue https://github.com/DynamicDevices/meta-mono/issues/168

### CODE REVIEW

**Comment by zboszor** [comment]
> @zboszor Can you have any idea what should went wrong after your new commit in [dotnet_6.0.403.bb](https://github.com/DynamicDevices/meta-mono/commit/97cfe3977222c5b437570651fb633a3a172531d9)? It seems to me it failed only in x86-64 build. `A fatal error occurred, the required library libhostfxr.so could not be found`

Most of the changes in that commit were not mine.
It's just that my fixes (two small commits, see #166 ) over this PR were squashed together with the big commit from #163

**Comment by kaspt** [comment]
I revoved the seperate installation from libhostfxr.so because the repository was archived. I think there are some symlinks missing or doesn't work. I spoted once for msbuild native when replace a symlink with a copy it works.

**Comment by ajlennon** [comment]
Just trying to catch up here. Not really clear why only the x86-64 build is failing ???

**Comment by ajlennon** [comment]
Confused. The .so it is missing is there...

**Comment by karthago1** [comment]
> A fatal error occurred, the required library libhostfxr.so could not be found in [/__w/meta-mono/meta-mono/langdale/build/tmp/work/core2-64-poky-linux/python3-pythonnet/3.0.1+gitAUTOINC+e28dd80c3a-r0/recipe-sysroot-native/usr/share/dotnet/host/fxr/7.0.4]

7.0.4 this version is available only in my [Pull Request](https://github.com/DynamicDevices/meta-mono/pull/167)

I think this is maybe CI/sstate cache Problem?. most probably if you merge that PR then this PR will be successful

**Comment by ajlennon** [comment]
Excellent - thanks @Livius90 !

**Pull request merged**
