### PR TITLE
Sync merged mickledore to master

### PR DESCRIPTION
**Pull request by Livius90**
Sync merged mickledore to master, master have to be merged to mickledore later.

### CODE REVIEW

**Comment by Livius90** [comment]
@ajlennon 
I suggest to do not use squash at merging just now, to avoid git crazy diffs analyzing between two branches.

**Comment by ajlennon** [comment]
The only option it'll let me do is the squash and merge @Livius90 ?

**Comment by ajlennon** [comment]
image

image

**Comment by ajlennon** [comment]
What do you think. Shall I just squash merge or do you want to have a go at pushing something I can merge in without squash ?

**Comment by Livius90** [comment]
now, need to merge back mickledore to master to get fully synced both

**Pull request closed without merging**
