### PR TITLE
Ajl/add ci settings to readme

### PR DESCRIPTION
**Pull request by ajlennon**

### CODE REVIEW

**Comment by ajlennon** [comment]
Interesting - looks like it's time to look at security

```
ERROR: test-image-mono-1.0-r0 do_rootfs: No SPDX file found for package dotnet, False sstate:dotnet:core2-64-poky-linux:6.0.417:r0:core2-64:11: sstate:dotnet::6.0.417:r0::11:
```

**Comment by Livius90** [comment]
You will have to merge/sync with master branch if you like to test here the fixed CI build.

**Comment by ajlennon** [comment]
Ah yes! Thanks

**Comment by Livius90** [comment]
From now unfortunately the builds time are much more, only working solution was to use `-c cleanall` for some important recipes to avoid this SPDX issue.

https://github.com/DynamicDevices/meta-mono/blob/master/.github/workflows/CI_github.yml#L82

**Comment by ajlennon** [comment]
> From now unfortunately the builds time are much more, only working solution was to use `-c cleanall` for some important recipes to avoid this SPDX issue.
> 
> https://github.com/DynamicDevices/meta-mono/blob/master/.github/workflows/CI_github.yml#L82

Ouch. OK well thanks for looking into this! I'd been meaning to work out what we need to do here. I've been following some of the OpenEmbedded conversations about SPDX and SBOMS and so forth. It seems a very good idea to support SBOMs and track CVEs but I suspect makes everything much more complicated.

The `-c cleanall` thing isn't ideal is it. Can you give me an idea why this is needed? For example, if I wiped the existing build trees for all the branches (which I effectively just did by rebuilding the CI VM) would we still need the `-c cleanall` as I'd really like not to have even longer build times. What do you think?

**Comment by Livius90** [comment]
Most of time this is the error: `"No SPDX file found for package dotnet"`

It means somewhy the SPDX file was lost in Yocto project, and my exeprience was that -c cleanall is the only one which can solve it because it re fatch and rebuild the recipes.

We can also start to optimize with use of `bitbake -c cleanall dotnet dtonet-native`. If issue is affected only for dotnet recipe.

**Comment by ajlennon** [comment]
>We can also start to optimize with use of bitbake -c cleanall dotnet dotnet-native. If issue is affected only for dotnet recipe.

So we think sometimes the SPDX creation works for the dotnet recipe and sometimes it doesn't?

**Comment by Livius90** [comment]
> > We can also start to optimize with use of bitbake -c cleanall dotnet dotnet-native. If issue is affected only for dotnet recipe.
> 
> So we think sometimes the SPDX creation works for the dotnet recipe and sometimes it doesn't?

Yes, moreover if the recipe has no any changes, it can happened. But if it was cleaned then refetched and rebuilt, it has no problem.

**Comment by Livius90** [comment]
@ajlennon 
From this https://github.com/DynamicDevices/meta-mono/pull/212 PR, build time is much faster, it is about 10 minutes for each job.

**Comment by ajlennon** [comment]
> From this #212 PR, build time is much faster, it is about 10 minutes for each job.

Nicely done :-D

**Pull request merged**
