### PR TITLE
Raising my own PR on #159 to look at the python3 build problem independently

### PR DESCRIPTION
**Pull request by ajlennon**

### CODE REVIEW

**Comment by Livius90** [comment]
"Starting with Kirkstone, compilation steps are not allowed to use the network (to improve reproducibility and reduce the chances of data exfiltration). If your build process requires network access during the build, you must specify it in the recipe."
https://low-level.wiki/yocto/kirkstone-upgrade.html
```
+do_configure[network] = "1"
+do_compile[network] = "1"
```

What a hell, it is a new thing from kirkstone, i hope it could fix it some hours and we can see the result. :open_mouth:
But i can not understand how can works without it in my phisical machine on my kirkstone Yocto project of our custom boards.

**Comment by ajlennon** [comment]
Yes this is what I was saying to you and this is what I've added

**Comment by Livius90** [comment]
I am very optimistic now, the bitbake process has never reached such a high task steps over 6000 without any error. I am feeling, it works. :relaxed:

**Comment by ajlennon** [comment]
yes the whole "no network" change is very irritating isn't it as it's not widely explained. I hadn't heard about it until @zboszor (I think) pointed it out to me

**Comment by Livius90** [comment]
I can not find any official Yocto guide for it, also.

**Comment by ajlennon** [comment]
Looks like a different error now which seems positive

**Comment by Livius90** [comment]
victory is near

**Comment by Livius90** [comment]
@ajlennon 
Finally everything is working well, i fixed the last issue in my PR.
https://github.com/DynamicDevices/meta-mono/pull/159

But please wait for final merging until tomorrow, because i would like to test `do_compile[network] = "1"` in my physical Ubuntu machine behind proxy. Maybe there are no need to do any proxy workaround in the recipe environments then it can be removed or commented out forever.

**Comment by ajlennon** [comment]
Hurray! Awesome! I knew we'd get there. Yes that sounds a great idea. If you could prove out it works ok and then strip back the commits relating to the proxy stuff that would be awesome.

Also super interested to hear what you're doing with this Python wrapper stuff. 

It would be fantastic if you could submit some simple test cases we could use to verify this works 

Happy to help with how to do that

**Comment by Livius90** [comment]
Python.NET has own standard [unit-tests](https://github.com/pythonnet/pythonnet/tree/master/tests) which uses [pytest framework](https://docs.pytest.org/en/7.2.x/) on their git repo. Maybe the full test-case list is runnable in Yocto qemu test.

**Comment by ajlennon** [comment]
I think we've shown the key issue here was that bitbake now disallows network access during compile step by default.

**Pull request closed without merging**
