### PR TITLE
Backport mono fixes to Kirkstone

### PR DESCRIPTION
**Pull request by niraami**
Backport fixes from:
- #239 
- #240 
- #241

### CODE REVIEW

**Comment by niraami** [comment]
I can do this for the rest of the branches as well if you don't mind.

**Comment by niraami** [comment]
Holy ... those pipelines take forever to run! Are you rebuilding everything from scratch on purpose? If you can, you should have an sstate & downloads cache, that would drastically reduce your build times.

**Comment by ajlennon** [comment]
No we're actually not rebuilding everything from scratch. It does seem to have slowed down drastically though and I'm not sure why. It might be that I cleared out the workspace a while ago and it's not rebuild kirkstone for a while. If you fancy adding in any speed optimisations please shoot a PR!

And yes please if you can create some PRs for the other branches that would be super!

**Comment by ajlennon** [comment]
ok I think I've added SSTATE_DIR into master - will see how that works out

**Comment by niraami** [comment]
> It might be that I cleared out the workspace a while ago and it's not rebuilt kirkstone for a while.

That actually makes a lot of sense, I'm just too used to working with Kirkstone I guess.

> ok I think I've added SSTATE_DIR into master - will see how that works out

I've looked at your pipeline a bit more closely, and it doesn't seem like you wipe the workspace, so changing the sstate dir might not have been necessary - but it's good practice to have it outside of the build folder anyways, cause then you can just wipe everything and not have to worry.

Also, about sstate, if you ever have issues with it growing way too large, you can safely clean it out with commands like these:
```
// Remove any cache files that haven't been accessed in over a month
find ${CACHE_DIR}/sstate -type f -atime +30 -delete
// Remove duplicate sstate files
./poky/scripts/sstate-cache-management.sh --cache-dir=${CACHE_DIR}/sstate --remove-duplicated --yes --verbose
```
Source: https://docs.yoctoproject.org/dev-manual/disk-space.html

**Comment by niraami** [comment]
I'll make those backport PRs then, and I'll think about the CI/CD improvements, there's not that many things you can do, other than caching properly and throwing cores (and a fast disk) at the build machine xD

**Comment by ajlennon** [comment]
Yeah that's what I was thinking. One SSTATE_DIR for everything so if I do wipe the build folders in future I can keep that.

And I wasn't aware of the cache management stuff - that's cool - thanks !

**Comment by ajlennon** [comment]
Merged thanks!

**Pull request merged**
